### ISSUE TITLE
QWeb installation problem - Ubuntu 24.04

### ISSUE THREAD

**Issue by ivansilvestre** [qentinelqi/qweb#159]
Hello!

I use ubuntu 24.04 and I'm trying to install QWeb on the system but it always returns an error as shown in the attachment.

I've already installed the most up-to-date library from the "scikit-image" package separately, but Qweb still tries to install an older version.
How can I solve this?

Thanks
![Screenshot from 2024-07-26 09-38-21](https://github.com/user-attachments/assets/38f37ab0-662a-4103-9d4d-f78acec5c135)

**Comment by tkoukkari** [comment]
Thank you for reporting this. 
Sorry for the delay, it has been a summer holiday season here. We will check this.

**Comment by tkoukkari** [comment]
@ivansilvestre can you please confirm that you have python version 3.12 in use? If yes, then that would explain it since not all dependencies yet support python 3.12 (and we've not marked that as supported version either, yet).

We need to allow later versions of scikit-image (after testing) in next QWeb version.

Meanwhile, a possible workarounds would be to install python 3.11:
```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update
sudo apt install python3.11 python3.11-dev python3.11-tk scrot
...
python3.11 -m pip install -U setuptools
python3.11 -m pip install QWeb
# (this one might also be needed)
xhost + 
```
...or installing **pyenv** and using that to install lower python version.

I'll leave this issue open until we have upgraded scikit-image to later version.

**Comment by ivansilvestre** [comment]
Yes, I'm using python version 3.12. 
That's right!
Yeah, I only noticed afterwards that QWeb is only supported it up to 3.11. Then I couldn't delete my share.

Thanks tkoukkari :)

**Comment by tkoukkari** [comment]
Python 3.12 support should be improved in QWeb version 3.4.0
