### ISSUE TITLE
Some PDF text verifications would benefit from text normalization 

### ISSUE THREAD

**Issue by ansevala** [qentinelqi/qweb#6]
In some cases it is hard to verify texts in PDF files due to surprising amount of newline characters and/or extra spaces. It would be useful to have normalize_text kwarg (or something like that) in VerifyPdfText to help user with these verifications. Please see [my code example](https://github.com/ansevala/exploring-ethics) for more details.

**Comment by tkoukkari** [comment]
Agreed. The formatting in PDF sometimes affects on how/what is being read. We should add this as a configuration and/or argument as suggested. Thanks for the proposal!

**Comment by tkoukkari** [comment]
This issue is now fixed and will be part of next release. There is an additional argument **normalize** (default=False), which controls it. 

- Without giving the argument or giving it as False -> behaves as currently.
- When using **normalize=True** newlines are removed from the verification.

This works with **VerifyPdfText**, **VerifyNoPdfText**, **VerifyFileText** and **VerifyNoFileText**.  We decided to leave **Get*** keywords as they are, i.e. they will still return text as it is with newlines intact.
